export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText:true,
    lightTextDesc: true,
    topLine:'Ultimate System PenTesting',
    headline: 'Lock it down, protect it up, and block the hackers.',
    description:'Safeguards information system assets by identifying and solving potential and actual security problems. Protects system by defining access privileges, control structures, and resources. Recognizes problems by identifying abnormalities; reporting violations.',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/image1.jpg'),
    alt: 'Tech',
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText:false,
    lightTextDesc: false,
    topLine:'Ultimate System PenTesting',
    headline: 'Lock it down, protect it up, and block the hackers.',
    description:'Safeguards information system assets by identifying and solving potential and actual security problems. Protects system by defining access privileges, control structures, and resources. Recognizes problems by identifying abnormalities; reporting violations.',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/image2.jpg'),
    alt: 'Tech',
    dark: false,
    primary: false,
    darkText: true,
}
export const homeObjTree = {
    id: 'about',
    lightBg: false,
    lightText:true,
    lightTextDesc: true,
    topLine:'Ultimate System PenTesting',
    headline: 'Lock it down, protect it up, and block the hackers.',
    description:'Safeguards information system assets by identifying and solving potential and actual security problems. Protects system by defining access privileges, control structures, and resources. Recognizes problems by identifying abnormalities; reporting violations.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/image3.jpg'),
    alt: 'Tech',
    dark: true,
    primary: true,
    darkText: false,
}